from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .scanner import Finding, Report, analyze


def _finding_key(finding: Finding) -> tuple[str, str, str, str]:
    # Line numbers are intentionally excluded so harmless line shifts do not
    # turn an existing finding into a fake regression.
    return (finding.severity, finding.code, finding.file, finding.message)


@dataclass
class RegressionReport:
    base: Report
    head: Report
    delta: int
    new_findings: list[Finding]
    resolved_findings: list[Finding]

    @property
    def new_errors(self) -> list[Finding]:
        return [finding for finding in self.new_findings if finding.severity == "error"]

    def to_dict(self) -> dict:
        return {
            "base": self.base.to_dict(),
            "head": self.head.to_dict(),
            "delta": self.delta,
            "new_findings": [finding.to_dict() for finding in self.new_findings],
            "resolved_findings": [finding.to_dict() for finding in self.resolved_findings],
        }


def compare(base_root: Path, head_root: Path) -> RegressionReport:
    base = analyze(base_root)
    head = analyze(head_root)

    base_by_key = {_finding_key(finding): finding for finding in base.findings}
    head_by_key = {_finding_key(finding): finding for finding in head.findings}

    new_keys = head_by_key.keys() - base_by_key.keys()
    resolved_keys = base_by_key.keys() - head_by_key.keys()

    new_findings = sorted(
        (head_by_key[key] for key in new_keys),
        key=lambda finding: (finding.severity != "error", finding.code, finding.file, finding.line or 0),
    )
    resolved_findings = sorted(
        (base_by_key[key] for key in resolved_keys),
        key=lambda finding: (finding.severity != "error", finding.code, finding.file, finding.line or 0),
    )

    return RegressionReport(
        base=base,
        head=head,
        delta=head.score - base.score,
        new_findings=new_findings,
        resolved_findings=resolved_findings,
    )


def markdown_report(report: RegressionReport) -> str:
    sign = "+" if report.delta > 0 else ""
    status = "✅ No regression" if report.delta >= 0 and not report.new_errors else "⚠️ Regression detected"
    lines = [
        "## AgentConfigScore regression",
        "",
        f"**{status}**",
        "",
        f"| Base | Head | Delta | New findings | Resolved |",
        f"| ---: | ---: | ---: | ---: | ---: |",
        f"| {report.base.score}/100 ({report.base.grade}) | {report.head.score}/100 ({report.head.grade}) | {sign}{report.delta} | {len(report.new_findings)} | {len(report.resolved_findings)} |",
    ]

    if report.new_findings:
        lines.extend(["", "### New findings", ""])
        for finding in report.new_findings:
            location = finding.file + (f":{finding.line}" if finding.line else "")
            lines.append(f"- **{finding.severity.upper()}** `{finding.code}` — {finding.message} (`{location}`)")

    if report.resolved_findings:
        lines.extend(["", "### Resolved findings", ""])
        for finding in report.resolved_findings:
            location = finding.file + (f":{finding.line}" if finding.line else "")
            lines.append(f"- ~~`{finding.code}` — {finding.message} (`{location}`)~~")

    lines.extend(["", "_Generated by AgentConfigScore. Only regressions matter._", ""])
    return "\n".join(lines)
